version: '3'
services:
  ansible:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile
    image: result/latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./:/home
      - /var/run/docker.sock:/var/run/docker.sock

# steps:
# 1. if not created
# molecule init role isri.redis --driver-name docker --verifier-name testinfra

# 2.
# docker-compose up -d
# docker-compose exec ansible bash
# 3.
# python3 -m venv .venv

#4. to shut down the container and remove image
# remove image : docker-compose down --rmi local
# leave image : docker-compose down
