version: '3'
services:
  ansible:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile
    image: result/latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # environment:
    #   ANSIBLE_CONFIG: ../ansible.cfg
    volumes:
      # - ./:/home      - /var/run/docker.sock:/var/run/docker.sock
      - ./ansible.cfg:/etc/ansible/ansible.cfg

# steps:
###### interactive shell
# docker-compose exec -w /home ansible bash
# 1. if not created
# molecule init role isri.redis --driver-name docker --verifier-name testinfra

# 2.
# docker-compose up -d
# docker-compose exec -w /home/ ansible bash
######## virtual env #########
# 1. create the virtual env if it doesnt exist
# python -m venv $VIRTUAL_ENV
# source $VIRTUAL_ENV/bin/activate
# Install Ansible via Pip.
# pip install --user $pip_packages

#3 to shut down the container and remove image
# remove image : docker-compose down -v --rmi local

# ansible-galaxy role init my_role
# cd my_role
# molecule init scenario

# cd ansible-role-splunk-forwarder
# molecule init scenario default —role-name redis --driver-name docker --verifier-name testinfra
