version: '3'
services:
  ansible:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile
    image: result/latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # environment:
    #   ANSIBLE_CONFIG: ../ansible.cfg
    volumes:
      - ./:/home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ansible.cfg:/etc/ansible/ansible.cfg

# steps:
# 1. if not created
# molecule init role isri.redis --driver-name docker --verifier-name testinfra

# 2.
# docker-compose up -d
# docker-compose exec -w /home/redis ansible bash

# 3.
# python3.9 -m venv .venv
# source .env/bin/activate
# update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2
# update-alternatives --set python3 /usr/bin/python3.9

#4. to shut down the container and remove image
# remove image : docker-compose down --rmi local
# leave image : docker-compose down

# /usr/local/bin/python3.9
# /usr/local/include/python3.9
# /usr/local/lib/python3.9
# /home/redis/venv39/bin/python3.9
# /home/redis/venv39/lib/python3.9


# curl https://pyenv.run | bash
# echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
# echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
# echo 'eval "$(pyenv init -)"' >> ~/.bashrc
